### ISSUE TITLE
No metrics on AWS/EC2 dashboard

### ISSUE THREAD

**Issue by GPavlovic** [logzio/docker-collector-metrics#14]
I have configured the `aws` module as described [here in the docs](https://app.logz.io/#/dashboard/data-sources/EC2-metrics) but there are no metrics collected when I look at the AWS/EC2 dashboard: 
![Screenshot_2020-05-24 Metrics - Logz io](https://user-images.githubusercontent.com/5474337/82754112-d4dc0400-9d98-11ea-8f1d-f344a41ac32e.png)

I have left it to run overnight, nothing ever showed. Interestingly, the `Cloudwatch AWS/EC2` dashboard **does** show data.

I also have the `docker` module running, and that works. Any ideas as to why this would not work?

**Comment by schwin007** [comment]
Hi @GPavlovic can you please email our support team at help@logz.io with the command you ran and the logs from the metricbeat container for review.

**Comment by schwin007** [comment]
Hi @GPavlovic I checked your account and I can see you had an outdated version of the EC2 Metrics dashboards in your account, I just updated it to the newer version "Cloudwatch AWS/EC2 
" you should see that dashboard populated now.

**Comment by GPavlovic** [comment]
So that dashboard does populate, but the `AWS EC2` dashboard shows nothing. I guess that is expected then? The documentation still references that old dashboard then, maybe that should be updated (unless I am misunderstanding)

https://app.logz.io/#/dashboard/data-sources/EC2-metrics

**Comment by Doron-Bargo** [comment]
Hi @GPavlovic - Do you still have problem or we can close this issue?
